"""
Populate the goods output modifier matrix from historical region rankings.
Values derived from region_yield_rankings_1300_1500.md.
Bounds: [-0.35, 0.35] per cell.
"""

import os

import pandas as pd

from analysis.building_levels.building_analysis import get_path
from analysis.building_levels.scripts.generate_goods_modifier_matrix import (
    ATTRIBUTES,
    GOODS,
)

# Per (good, attr): modifier. Bounds [-0.35, 0.35].
# Derived from historical best/worst regions: mediterranean→fruit+olives,
# coastal+cold→fish, grasslands+continental→wool/livestock, dry→millet,
# irrigated flatland→wheat/rice/legumes, tropical hills→maize, plateau/mountains→potato,
# forest/woods→wild_game/fur, arctic/continental→fur.
MATRIX = {
    "fruit": {
        "flatland": 0.10,
        "hills": 0.20,
        "plateau": 0.05,
        "mountains": -0.20,
        "wetlands": -0.30,
        "salt_pans": -0.70,
        "atoll": 0.15,
        "desert": -0.50,
        "sparse": -0.20,
        "grasslands": 0.10,
        "farmland": 0.20,
        "woods": 0.10,
        "forest": 0.05,
        "jungle": 0.10,
        "tropical": 0.15,
        "subtropical": 0.20,
        "oceanic": 0.05,
        "arid": -0.30,
        "cold_arid": -0.50,
        "mediterranean": 0.25,
        "continental": 0.05,
        "arctic": -0.80,
        "has_river": 0.15,
        "is_adjacent_to_lake": 0.08,
        "is_coastal": 0.05,
    },
    "fish": {
        "flatland": 0.00,
        "hills": 0.00,
        "plateau": -0.30,
        "mountains": -0.50,
        "wetlands": 0.05,
        "salt_pans": 0.15,
        "atoll": 0.20,
        "desert": -0.60,
        "sparse": -0.20,
        "grasslands": 0.00,
        "farmland": 0.00,
        "woods": 0.00,
        "forest": 0.02,
        "jungle": 0.02,
        "tropical": 0.05,
        "subtropical": 0.05,
        "oceanic": 0.20,
        "arid": -0.50,
        "cold_arid": -0.30,
        "mediterranean": 0.10,
        "continental": 0.05,
        "arctic": 0.15,
        "has_river": 0.10,
        "is_adjacent_to_lake": 0.15,
        "is_coastal": 0.25,
    },
    "wool": {
        "flatland": 0.15,
        "hills": 0.20,
        "plateau": 0.15,
        "mountains": 0.05,
        "wetlands": -0.50,
        "salt_pans": -0.60,
        "atoll": -0.80,
        "desert": -0.60,
        "sparse": 0.10,
        "grasslands": 0.25,
        "farmland": 0.15,
        "woods": 0.10,
        "forest": 0.05,
        "jungle": -0.70,
        "tropical": -0.30,
        "subtropical": 0.05,
        "oceanic": 0.10,
        "arid": -0.40,
        "cold_arid": -0.20,
        "mediterranean": 0.15,
        "continental": 0.25,
        "arctic": -0.60,
        "has_river": 0.08,
        "is_adjacent_to_lake": 0.05,
        "is_coastal": 0.00,
    },
    "livestock": {
        "flatland": 0.20,
        "hills": 0.15,
        "plateau": 0.10,
        "mountains": -0.10,
        "wetlands": -0.40,
        "salt_pans": -0.50,
        "atoll": -0.80,
        "desert": -0.70,
        "sparse": 0.15,
        "grasslands": 0.25,
        "farmland": 0.15,
        "woods": 0.05,
        "forest": -0.20,
        "jungle": -0.80,
        "tropical": -0.40,
        "subtropical": 0.05,
        "oceanic": 0.08,
        "arid": -0.50,
        "cold_arid": -0.20,
        "mediterranean": 0.15,
        "continental": 0.25,
        "arctic": -0.70,
        "has_river": 0.15,
        "is_adjacent_to_lake": 0.10,
        "is_coastal": 0.00,
    },
    "millet": {
        "flatland": 0.15,
        "hills": 0.10,
        "plateau": 0.15,
        "mountains": 0.00,
        "wetlands": -0.50,
        "salt_pans": -0.30,
        "atoll": -0.20,
        "desert": 0.10,
        "sparse": 0.20,
        "grasslands": 0.15,
        "farmland": 0.10,
        "woods": 0.05,
        "forest": 0.00,
        "jungle": -0.50,
        "tropical": 0.15,
        "subtropical": 0.10,
        "oceanic": -0.20,
        "arid": 0.20,
        "cold_arid": 0.10,
        "mediterranean": 0.08,
        "continental": 0.15,
        "arctic": -0.80,
        "has_river": 0.05,
        "is_adjacent_to_lake": 0.00,
        "is_coastal": 0.00,
    },
    "wheat": {
        "flatland": 0.25,
        "hills": 0.15,
        "plateau": 0.10,
        "mountains": -0.30,
        "wetlands": -0.20,
        "salt_pans": -0.70,
        "atoll": -0.60,
        "desert": -0.70,
        "sparse": 0.05,
        "grasslands": 0.20,
        "farmland": 0.25,
        "woods": 0.05,
        "forest": -0.10,
        "jungle": -0.80,
        "tropical": -0.30,
        "subtropical": 0.15,
        "oceanic": 0.10,
        "arid": -0.50,
        "cold_arid": -0.30,
        "mediterranean": 0.20,
        "continental": 0.25,
        "arctic": -0.90,
        "has_river": 0.20,
        "is_adjacent_to_lake": 0.08,
        "is_coastal": 0.00,
    },
    "maize": {
        "flatland": 0.15,
        "hills": 0.20,
        "plateau": 0.15,
        "mountains": -0.20,
        "wetlands": -0.40,
        "salt_pans": -0.60,
        "atoll": 0.05,
        "desert": -0.50,
        "sparse": 0.10,
        "grasslands": 0.15,
        "farmland": 0.20,
        "woods": 0.10,
        "forest": 0.05,
        "jungle": -0.30,
        "tropical": 0.20,
        "subtropical": 0.25,
        "oceanic": -0.10,
        "arid": 0.05,
        "cold_arid": -0.50,
        "mediterranean": 0.05,
        "continental": -0.20,
        "arctic": -1.00,
        "has_river": 0.15,
        "is_adjacent_to_lake": 0.08,
        "is_coastal": 0.00,
    },
    "rice": {
        "flatland": 0.25,
        "hills": 0.10,
        "plateau": -0.20,
        "mountains": -0.50,
        "wetlands": 0.20,
        "salt_pans": -0.70,
        "atoll": 0.05,
        "desert": -0.80,
        "sparse": -0.20,
        "grasslands": 0.10,
        "farmland": 0.20,
        "woods": 0.05,
        "forest": 0.05,
        "jungle": 0.15,
        "tropical": 0.20,
        "subtropical": 0.25,
        "oceanic": 0.05,
        "arid": -0.70,
        "cold_arid": -0.60,
        "mediterranean": 0.10,
        "continental": 0.05,
        "arctic": -1.00,
        "has_river": 0.25,
        "is_adjacent_to_lake": 0.15,
        "is_coastal": 0.05,
    },
    "legumes": {
        "flatland": 0.20,
        "hills": 0.15,
        "plateau": 0.05,
        "mountains": -0.10,
        "wetlands": 0.05,
        "salt_pans": -0.60,
        "atoll": -0.20,
        "desert": -0.50,
        "sparse": 0.05,
        "grasslands": 0.15,
        "farmland": 0.25,
        "woods": 0.08,
        "forest": 0.05,
        "jungle": 0.05,
        "tropical": 0.10,
        "subtropical": 0.20,
        "oceanic": 0.08,
        "arid": -0.30,
        "cold_arid": -0.20,
        "mediterranean": 0.25,
        "continental": 0.10,
        "arctic": -0.60,
        "has_river": 0.20,
        "is_adjacent_to_lake": 0.10,
        "is_coastal": 0.00,
    },
    "potato": {
        "flatland": 0.15,
        "hills": 0.20,
        "plateau": 0.25,
        "mountains": 0.20,
        "wetlands": -0.50,
        "salt_pans": -0.70,
        "atoll": -0.50,
        "desert": -0.60,
        "sparse": 0.10,
        "grasslands": 0.15,
        "farmland": 0.20,
        "woods": 0.05,
        "forest": 0.00,
        "jungle": -0.60,
        "tropical": -0.40,
        "subtropical": 0.05,
        "oceanic": 0.15,
        "arid": -0.30,
        "cold_arid": 0.05,
        "mediterranean": 0.10,
        "continental": 0.15,
        "arctic": -0.50,
        "has_river": 0.10,
        "is_adjacent_to_lake": 0.05,
        "is_coastal": 0.00,
    },
    "olives": {
        "flatland": 0.15,
        "hills": 0.25,
        "plateau": 0.10,
        "mountains": 0.05,
        "wetlands": -0.50,
        "salt_pans": -0.70,
        "atoll": -0.80,
        "desert": -0.40,
        "sparse": 0.10,
        "grasslands": 0.15,
        "farmland": 0.20,
        "woods": 0.08,
        "forest": 0.05,
        "jungle": -0.60,
        "tropical": -0.50,
        "subtropical": 0.15,
        "oceanic": -0.20,
        "arid": 0.05,
        "cold_arid": -0.50,
        "mediterranean": 0.25,
        "continental": -0.30,
        "arctic": -0.90,
        "has_river": 0.10,
        "is_adjacent_to_lake": 0.05,
        "is_coastal": 0.08,
    },
    "leather": {
        "flatland": 0.15,
        "hills": 0.10,
        "plateau": 0.08,
        "mountains": -0.05,
        "wetlands": -0.40,
        "salt_pans": -0.50,
        "atoll": -0.70,
        "desert": -0.50,
        "sparse": 0.10,
        "grasslands": 0.20,
        "farmland": 0.15,
        "woods": 0.05,
        "forest": -0.10,
        "jungle": -0.50,
        "tropical": -0.30,
        "subtropical": 0.05,
        "oceanic": 0.05,
        "arid": -0.40,
        "cold_arid": -0.10,
        "mediterranean": 0.10,
        "continental": 0.20,
        "arctic": -0.50,
        "has_river": 0.08,
        "is_adjacent_to_lake": 0.05,
        "is_coastal": 0.00,
    },
    "wild_game": {
        "flatland": -0.10,
        "hills": 0.15,
        "plateau": 0.10,
        "mountains": 0.20,
        "wetlands": 0.05,
        "salt_pans": -0.80,
        "atoll": -0.50,
        "desert": -0.70,
        "sparse": 0.05,
        "grasslands": 0.05,
        "farmland": -0.30,
        "woods": 0.25,
        "forest": 0.25,
        "jungle": 0.15,
        "tropical": 0.05,
        "subtropical": 0.05,
        "oceanic": 0.08,
        "arid": -0.60,
        "cold_arid": -0.20,
        "mediterranean": 0.08,
        "continental": 0.15,
        "arctic": 0.05,
        "has_river": 0.05,
        "is_adjacent_to_lake": 0.08,
        "is_coastal": 0.00,
    },
    "fur": {
        "flatland": 0.00,
        "hills": 0.10,
        "plateau": 0.10,
        "mountains": 0.15,
        "wetlands": 0.05,
        "salt_pans": -0.80,
        "atoll": -0.90,
        "desert": -0.70,
        "sparse": 0.10,
        "grasslands": 0.00,
        "farmland": -0.20,
        "woods": 0.15,
        "forest": 0.25,
        "jungle": -0.80,
        "tropical": -0.80,
        "subtropical": -0.40,
        "oceanic": -0.10,
        "arid": -0.50,
        "cold_arid": 0.10,
        "mediterranean": -0.50,
        "continental": 0.15,
        "arctic": 0.25,
        "has_river": 0.05,
        "is_adjacent_to_lake": 0.08,
        "is_coastal": 0.00,
    },
}


def clamp(val: float, lo: float = -0.35, hi: float = 0.35) -> float:
    return max(lo, min(hi, val))


def main():
    data_dir = get_path("data_dir")
    output_path = os.path.join(data_dir, "goods_output_modifiers.xlsx")

    rows = []
    for good in GOODS:
        row = {"good": good}
        for attr in ATTRIBUTES:
            v = MATRIX.get(good, {}).get(attr, 0.0)
            row[attr] = clamp(v)
        rows.append(row)

    df = pd.DataFrame(rows).set_index("good")

    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Matrix")
        info_df = pd.DataFrame(
            {
                "Info": [
                    "Per-cell bounds: [-0.35, 0.35]",
                    "Sum across applicable attributes. Values from region_yield_rankings_1300_1500.md.",
                ]
            }
        )
        info_df.to_excel(writer, sheet_name="Info", index=False)

    print(f"Matrix populated and written to {output_path}")
    min_v = df.min().min()
    max_v = df.max().max()
    print(f"Value range: {min_v:.2f} to {max_v:.2f}")


if __name__ == "__main__":
    main()
