"""Parse vanilla EU5 goods and emit pp_rgo_static_bonuses.txt, English loc, and on_action snippet."""
from __future__ import annotations

import re
from pathlib import Path

GAME_GOODS = Path(r"c:\Games\steamapps\common\Europa Universalis V\game\in_game\common\goods")
MOD_ROOT = Path(
    r"c:\Users\Anwender\Documents\Paradox Interactive\Europa Universalis V\mod"
    r"\Prosper or Perish (Population Growth & Food Rework)"
)
MOD_OUT = MOD_ROOT / "in_game" / "common" / "static_modifiers" / "pp_rgo_static_bonuses.txt"
# Same mod: on_action next to static_modifiers under in_game/common/
PP_GAME_START = MOD_ROOT / "in_game" / "common" / "on_action" / "pp_game_start.txt"
MOD_L10N_EN = MOD_ROOT / "main_menu" / "localization" / "english" / "pp_rgo_modifiers_l_english.yml"
# Optional: paste into pp_game_start.txt pp_apply_rgo_static_modifiers when good list changes
TOOLS_SNIPPET = Path(__file__).resolve().parent / "pp_rgo_on_action_snippet.txt"


def local_output_key(good: str) -> str:
    if good == "goods_gold":
        return "local_goods_gold_output_modifier"
    return f"local_{good}_output_modifier"


def parse_raw_material_goods(goods_dir: Path | None = None) -> dict[str, float | None]:
    """Parse all vanilla goods with category = raw_material; food value if food = X is set."""
    base = goods_dir if goods_dir is not None else GAME_GOODS
    goods: dict[str, float | None] = {}
    for path in sorted(base.glob("*.txt")):
        if path.name == "readme.txt":
            continue
        text = path.read_text(encoding="utf-8-sig")
        for m in re.finditer(r"^(\w+)\s*=\s*\{", text, re.MULTILINE):
            i = m.start()
            depth = 0
            j = i
            while j < len(text):
                if text[j] == "{":
                    depth += 1
                elif text[j] == "}":
                    depth -= 1
                    if depth == 0:
                        end = j + 1
                        break
                j += 1
            else:
                continue
            block = text[i:end]
            if "category = raw_material" not in block:
                continue
            name = m.group(1)
            food_m = re.search(r"^\s*food = ([0-9.]+)", block, re.MULTILINE)
            food = float(food_m.group(1)) if food_m else None
            goods[name] = food
    return goods


def parse_pp_rgo_bonus_good_ids(static_modifiers_path: Path) -> set[str]:
    """Return good ids from pp_rgo_bonus_<id> = { lines in pp_rgo_static_bonuses.txt."""
    text = static_modifiers_path.read_text(encoding="utf-8")
    found = re.findall(r"^pp_rgo_bonus_(\w+) = \{", text, re.MULTILINE)
    return set(found)


def parse_pp_rgo_goods_from_game_start(game_start_path: Path) -> set[str]:
    """Return good ids referenced by modifier = pp_rgo_bonus_<id> in pp_game_start.txt."""
    text = game_start_path.read_text(encoding="utf-8")
    found = re.findall(r"modifier = pp_rgo_bonus_(\w+)", text)
    return set(found)


def parse_pp_rgo_loc_good_ids(loc_yml_path: Path) -> set[str]:
    """Return good ids from STATIC_MODIFIER_NAME_pp_rgo_bonus_<id> keys in English loc."""
    text = loc_yml_path.read_text(encoding="utf-8")
    found = re.findall(r"^STATIC_MODIFIER_NAME_pp_rgo_bonus_(\w+):", text, re.MULTILINE)
    return set(found)


def emit_modifiers(goods: dict[str, float | None]) -> str:
    lines: list[str] = [
        "# Prosper or Perish — +10% local output for each location's RGO; food RGOs also adjust peasant food consumption.",
        "# Generated by tools/emit_pp_rgo_modifiers.py from vanilla goods (food = X → local_peasants_food_consumption = -X/100).",
        "",
    ]
    for name in sorted(goods.keys()):
        mod_name = f"pp_rgo_bonus_{name}"
        lines.append(f"{mod_name} = {{")
        lines.append("\tgame_data = { category = location }")
        key = local_output_key(name)
        lines.append(f"\t{key} = 0.10")
        food = goods[name]
        if food is not None and food > 0:
            peas = -food / 100.0
            peas_str = f"{peas:.6f}".rstrip("0").rstrip(".")
            if peas_str == "-0":
                peas_str = "0.0"
            lines.append(f"\tlocal_peasants_food_consumption = {peas_str}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def emit_localization(goods: dict[str, float | None]) -> str:
    """STATIC_MODIFIER_NAME / DESC for each pp_rgo_bonus_<good>; uses ShowGoodsName for vanilla good titles."""
    lines: list[str] = [
        "# Prosper or Perish — RGO static modifier display names (generated by tools/emit_pp_rgo_modifiers.py).",
        "l_english:",
    ]
    for name in sorted(goods.keys()):
        sn = f"pp_rgo_bonus_{name}"
        show = f"[ShowGoodsName('{name}')]"
        lines.append(f'STATIC_MODIFIER_NAME_{sn}: "Natural {show} Output"')
        food = goods[name]
        if food is not None and food > 0:
            desc = (
                f"Local output of {show} reflects this [location|e]'s natural [rgo|e]. "
                f"Local production also eases peasants' food needs."
            )
        else:
            desc = (
                f"Local output of {show} reflects this [location|e]'s natural [rgo|e]."
            )
        lines.append(f'STATIC_MODIFIER_DESC_{sn}: "{desc}"')
    return "\n".join(lines) + "\n"


def emit_on_action(goods: dict[str, float | None]) -> str:
    lines: list[str] = [
        "# Paste into pp_game_start.txt as pp_apply_rgo_static_modifiers (replace existing block).",
        "pp_apply_rgo_static_modifiers = {",
        "\teffect = {",
        "\t\tevery_location_in_the_world = {",
        "\t\t\tlimit = { exists = raw_material }",
    ]
    names = sorted(goods.keys())
    for i, name in enumerate(names):
        branch = "if" if i == 0 else "else_if"
        lines.append(f"\t\t\t{branch} = {{")
        lines.append(f"\t\t\t\tlimit = {{ raw_material = goods:{name} }}")
        lines.append("\t\t\t\tadd_location_modifier = {")
        lines.append(f"\t\t\t\t\tmodifier = pp_rgo_bonus_{name}")
        lines.append("\t\t\t\t\tmonths = -1")
        lines.append("\t\t\t\t\tmode = replace")
        lines.append("\t\t\t\t}")
        lines.append("\t\t\t}")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    goods = parse_raw_material_goods(GAME_GOODS)
    MOD_OUT.parent.mkdir(parents=True, exist_ok=True)
    MOD_OUT.write_text(emit_modifiers(goods), encoding="utf-8")
    MOD_L10N_EN.parent.mkdir(parents=True, exist_ok=True)
    MOD_L10N_EN.write_text(emit_localization(goods), encoding="utf-8")
    TOOLS_SNIPPET.write_text(emit_on_action(goods), encoding="utf-8")
    print(f"Wrote {MOD_OUT} ({len(goods)} goods)")
    print(f"Wrote {MOD_L10N_EN}")
    print(f"Wrote {TOOLS_SNIPPET}")


if __name__ == "__main__":
    main()
