# Regenerates Prosper or Perish per-good "output × market_access" map modes.
# Run from anywhere:
#   python tools/generate_pp_goods_output_map_modes.py
#
# Edits the mod under Documents (paths below). Do not edit *_generated* by hand.

from __future__ import annotations

import re
import shutil
from pathlib import Path

# -----------------------------------------------------------------------------
# Paths (edit if your install differs)
# -----------------------------------------------------------------------------

EU5_GAME = Path(r"C:\Games\steamapps\common\Europa Universalis V\game")
MOD_ROOT = Path(
    r"C:\Users\Anwender\Documents\Paradox Interactive\Europa Universalis V\mod"
    r"\Prosper or Perish (Population Growth & Food Rework)"
)

GOODS_DIR = EU5_GAME / "in_game" / "common" / "goods"
VICTUALS_GOODS = MOD_ROOT / "in_game" / "common" / "goods" / "pp_goods_victuals.txt"

OUT_SCRIPT = MOD_ROOT / "in_game" / "common" / "script_values" / "pp_goods_output_map_modes_generated.txt"
OUT_MAPMODES = MOD_ROOT / "in_game" / "gfx" / "map" / "map_modes" / "pp_goods_output_map_modes_generated.txt"
OUT_LOC = MOD_ROOT / "main_menu" / "localization" / "english" / "pp_goods_output_map_modes_l_english.yml"

VANILLA_TRADE_ICONS = EU5_GAME / "main_menu" / "gfx" / "interface" / "icons" / "trade_goods"
OUT_MAPMODE_ICONS = MOD_ROOT / "in_game" / "gfx" / "interface" / "icons" / "map_modes"

# Optional: omit goods from map modes (e.g. sensitive content).
EXCLUDED_GOODS: frozenset[str] = frozenset()

# Lerp factor = clamp(raw / PP_GOODS_OUTPUT_COLOR_SCALE_MAX, 0, 1); raw = output × market_access.
PP_GOODS_OUTPUT_COLOR_SCALE_MAX = 30

TOP_LEVEL_GOOD = re.compile(r"^([a-z_][a-z0-9_]*) = \{")


def parse_goods_file(path: Path) -> list[str]:
    """Only top-level `good_id = {` lines (column 0). Indented blocks are ignored."""
    ids: list[str] = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        line = line.rstrip("\n\r")
        if not line:
            continue
        if line.lstrip().startswith("#"):
            continue
        if line[0] in " \t":
            continue
        m = TOP_LEVEL_GOOD.match(line)
        if m:
            ids.append(m.group(1))
    return ids


def collect_good_ids() -> list[str]:
    found: set[str] = set()
    if not GOODS_DIR.is_dir():
        raise FileNotFoundError(f"Vanilla goods folder not found: {GOODS_DIR}")
    for p in sorted(GOODS_DIR.glob("*.txt")):
        if p.name.lower() == "readme.txt":
            continue
        for gid in parse_goods_file(p):
            found.add(gid)
    if VICTUALS_GOODS.is_file():
        for gid in parse_goods_file(VICTUALS_GOODS):
            found.add(gid)
    found -= EXCLUDED_GOODS
    return sorted(found)


def icon_source_for_good(good_id: str) -> Path | None:
    """Vanilla icons live in main_menu/.../trade_goods/icon_goods_<id>.dds."""
    p = VANILLA_TRADE_ICONS / f"icon_goods_{good_id}.dds"
    if p.is_file():
        return p
    # Mod-only good: same relative name under mod main_menu
    mod_p = (
        MOD_ROOT
        / "main_menu"
        / "gfx"
        / "interface"
        / "icons"
        / "trade_goods"
        / f"icon_goods_{good_id}.dds"
    )
    if mod_p.is_file():
        return mod_p
    mod_p2 = (
        MOD_ROOT
        / "in_game"
        / "gfx"
        / "interface"
        / "icons"
        / "trade_goods"
        / f"icon_goods_{good_id}.dds"
    )
    if mod_p2.is_file():
        return mod_p2
    return None


def write_script_values(goods: list[str]) -> None:
    lines = [
        "# Generated by tools/generate_pp_goods_output_map_modes.py — do not edit by hand.",
        "# Local monthly goods output × location market_access (cf. Location.GetMarketAccess).",
        "",
    ]
    for g in goods:
        lines.append(f"pp_{g}_output_raw = {{")
        lines.append(f'\tvalue = "goods_output(goods:{g})"')
        lines.append("\tmultiply = market_access")
        lines.append("}")
        lines.append("")
    OUT_SCRIPT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_map_modes(goods: list[str]) -> None:
    m = PP_GOODS_OUTPUT_COLOR_SCALE_MAX
    header = f"""# Generated by tools/generate_pp_goods_output_map_modes.py — do not edit by hand.
# Heatmap: raw = local output × market_access; color factor = clamp(raw / {m}, 0, 1) (0–{m} → red→green).
# Locations with zero local output of the good get no overlay (terrain); sea/unowned stay grey.

@pp_goods_output_color_scale_max = {m}

@zoom_step_near = 2
@data_gradient_alpha_inside = 1
@data_gradient_alpha_outside = 1
@data_gradient_width = 0.25
@data_gradient_color_mult = 0.9
@data_edge_width = 0
@data_edge_sharpness = 0.01
@data_edge_alpha = 0
@data_edge_color_mult = 0
@data_before_lighting_blend = 0.5
@data_after_lighting_blend = 0.5

"""
    blocks: list[str] = [header]
    for g in goods:
        u = g.upper()
        blocks.append(
            f"""pp_{g}_output = {{
	map_color = {{
		if = {{
			limit = {{
				has_owner = yes
				"goods_output(goods:{g})" > 0
			}}
			lerp = {{
				min_color = define:NMapColors|MAP_COLOR_LOW
				max_color = define:NMapColors|MAP_COLOR_HIGH
				factor = {{
					value = pp_{g}_output_raw
					divide = @pp_goods_output_color_scale_max
					max = 1
					min = 0
				}}
			}}
		}}
		else_if = {{
			limit = {{
				OR = {{
					NOT = {{ has_owner = yes }}
					is_land = no
				}}
			}}
			value = rgb {{ 128 128 128 }}
		}}
	}}
	legend_key = {{ desc = "MAPMODE_PP_{u}_OUTPUT" color = define:NMapColors|MAP_COLOR_HIGH }}
	tooltip_key = {{
		if = {{ limit = {{ is_land = yes }} value = MAPMODE_PP_{u}_OUTPUT_TT_LAND }}
		else = {{ value = MAPMODE_PP_{u}_OUTPUT_TT_WATER }}
	}}
	small_map_names = location
	medium_map_names = location
	large_map_names = location
	small_tooltip_context = location
	medium_tooltip_context = location
	large_tooltip_context = location
	fill_in_impassable = yes
	enable_snow = no
	flatmap_behaviour = always
	use_fow = no
	category = economy
	index = 3
	map_markers = {{ all = no }}
	gradient_parameters = {{
		zoom_step = @zoom_step_near
		gradient_alpha_inside = @data_gradient_alpha_inside
		gradient_alpha_outside = @data_gradient_alpha_outside
		gradient_width = @data_gradient_width
		gradient_color_mult = @data_gradient_color_mult
		edge_width = @data_edge_width
		edge_sharpness = @data_edge_sharpness
		edge_alpha = @data_edge_alpha
		edge_color_mult = @data_edge_color_mult
		before_lighting_blend = @data_before_lighting_blend
		after_lighting_blend = @data_after_lighting_blend
	}}
	color_refresh_counters = {{ Month ProductionList LocationConstructionUnitChanged MarketReach }}
	color_and_names_refresh_counters = {{ LocationOwnerChanged CountryStatus MarketReach }}
}}

"""
        )
    OUT_MAPMODES.write_text("".join(blocks), encoding="utf-8")


def yaml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_localization(goods: list[str]) -> None:
    m = PP_GOODS_OUTPUT_COLOR_SCALE_MAX
    lines = [
        "l_english:",
        '  # Generated by tools/generate_pp_goods_output_map_modes.py — do not edit by hand.',
    ]
    for g in goods:
        u = g.upper()
        name_val = f"[ShowGoodsName('{g}')|e] Output (× Market Access)"
        lines.append(f'  mapmode_pp_{g}_output_name: "{yaml_escape(name_val)}"')
        lines.append(
            f'  MAPMODE_PP_{u}_OUTPUT: "#T $mapmode_pp_{g}_output_name$#!\\nColors [locations|e] by local [ShowGoodsName(\'{g}\')|e] [output|e] × [market_access|e] from 0 (red) to {m}+ (green); values above {m} saturate."'
        )
        # ROOT.GetLocation — map mode tooltips have no free Location context (see localization_commands ScriptValue note).
        lines.append(
            f'  MAPMODE_PP_{u}_OUTPUT_TT_LAND: "#T $mapmode_pp_{g}_output_name$#!\\n[ROOT.GetLocation.GetName]: [ROOT.GetLocation.MakeScope.ScriptValue(\'pp_{g}_output_raw\')|2] = [ShowGoodsName(\'{g}\')|e] [output|e] × [market_access|e] (per month). Heatmap 0–{m}.\\n[market_access|e]: [ROOT.GetLocation.GetMarketAccess|2%V]."'
        )
        lines.append(
            f'  MAPMODE_PP_{u}_OUTPUT_TT_WATER: "$MAPMODE_PP_LOCAL_OUTPUT_TT_WATER$"'
        )
    lines.append("")
    OUT_LOC.write_text("\n".join(lines), encoding="utf-8-sig")


def copy_icons(goods: list[str]) -> None:
    OUT_MAPMODE_ICONS.mkdir(parents=True, exist_ok=True)
    missing: list[str] = []
    for g in goods:
        src = icon_source_for_good(g)
        dst = OUT_MAPMODE_ICONS / f"pp_{g}_output.dds"
        if src is None:
            missing.append(g)
            continue
        shutil.copy2(src, dst)
    if missing:
        print("Warning: no icon source for goods (map mode key still works; add DDS later):")
        for m in missing:
            print(f"  - {m}")


def main() -> None:
    goods = collect_good_ids()
    print(f"Found {len(goods)} goods (after exclusions).")
    write_script_values(goods)
    write_map_modes(goods)
    write_localization(goods)
    copy_icons(goods)
    print(f"Wrote:\n  {OUT_SCRIPT}\n  {OUT_MAPMODES}\n  {OUT_LOC}")
    print("Icons copied to:", OUT_MAPMODE_ICONS)


if __name__ == "__main__":
    main()
